#line 2 "scanner.cpp"

#line 4 "scanner.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 1
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yynoreturn yy_fatal_error (yyconst char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 92
#define YY_END_OF_BUFFER 93
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[335] =
    {   0,
        0,    0,   88,   88,    0,    0,   93,   85,   84,   77,
       16,   85,    7,   85,   85,   21,   22,    4,    2,   28,
        3,   27,    5,   80,   33,   29,   10,   31,   11,   32,
       30,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   25,   26,    6,
       23,   85,   24,   88,   90,   89,   92,   92,    9,    0,
       83,   14,    0,   82,   19,   17,   18,    1,   86,   20,
        0,   80,   12,    8,   13,   79,   79,   79,   79,   79,
       51,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,

       47,   79,   79,   79,   79,   79,   15,   88,   89,   89,
       91,   87,   86,   81,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   49,   79,   79,   79,   79,   79,
       79,   79,   79,   41,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   67,   79,   69,   56,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   48,   79,   79,
       79,   79,   79,   79,   79,   79,   35,   79,   79,   79,

       79,   79,   79,   79,   79,   78,   57,   59,   79,   79,
       79,   79,   79,   79,   40,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   66,   79,   68,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   70,   79,
       79,   79,   79,   79,   79,   79,   62,   79,   79,   79,
       79,   63,   79,   79,   79,   79,   61,   79,   79,   79,
       79,   79,   79,   79,   72,   52,   53,   79,   79,   79,
       79,   79,   79,   79,   79,   75,   79,   74,   58,   79,
       79,   79,   64,   79,   73,   71,   79,   79,   79,   36,
       79,   34,   42,   79,   60,   54,   79,   79,   46,   79,

       79,   79,   79,   55,   79,   37,   79,   38,   76,   79,
       79,   78,   43,   79,   79,   50,   79,   79,   79,   79,
       79,   79,   79,   65,   39,   79,   79,   79,   79,   79,
       79,   44,   45,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       35,   41,   42,   43,   44,   45,   35,   46,   35,   35,
       47,    1,   48,   49,   50,    1,   51,   52,   53,   54,

       55,   56,   57,   58,   59,   60,   35,   61,   62,   63,
       64,   65,   35,   66,   67,   68,   69,   70,   35,   71,
       35,   35,   72,   73,   74,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[75] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    1,    1,
        4,    1,    1,    1,    1,    1,    3,    1,    1,    1,
        1,    1,    1,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1,    1,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[343] =
    {   0,
        0,    0,   72,   73,  589,  587,  601,  637,  637,  637,
      578,  593,  637,  587,  584,  637,  637,  570,  566,  637,
      562,  637,   66,   63,  637,  637,  383,  337,  326,  637,
      637,    0,   40,   56,   56,   51,   61,   73,   51,   61,
       70,   75,   96,   76,  109,   81,  116,  637,  637,  637,
      637,  180,  637,    0,  637,   80,  637,  239,  637,  242,
      637,  637,  199,  637,  637,  637,  637,  637,    0,  637,
      186,   93,  637,  637,  637,    0,   70,  108,  105,   95,
      116,   93,  108,  109,  118,  128,  116,  123,  137,  142,
      154,  157,  157,  148,  148,  158,  161,  156,  156,  162,

      162,  175,  176,  167,  179,  167,  637,    0,  215,  219,
      637,  637,    0,  122,  184,  185,  195,  195,  211,  206,
      211,  213,  214,  215,  217,  206,  220,  208,  223,  216,
      217,  218,  223,  238,  222,  232,  249,  250,  246,  244,
      252,  265,  265,  251,  266,  258,  257,  272,  272,  277,
      271,  277,  277,  280,    0,  279,  285,  278,  285,  280,
      291,  286,  285,    0,  291,  296,  297,  314,  313,  302,
      312,   73,  321,  305,    0,  311,    0,    0,  327,  326,
      330,  327,  324,  320,  318,  321,  337,    0,  337,  344,
      333,  338,  338,  345,  355,  342,    0,  345,  351,  350,

      368,  354,  365,  359,  372,    0,    0,    0,  378,  362,
      370,  365,  375,  370,    0,  384,  382,  389,  387,  394,
      387,  392,  389,  401,  389,  406,    0,  404,    0,  411,
      404,  411,  416,  404,  407,  417,  416,  416,    0,  417,
       65,  433,  426,  432,  433,  439,    0,  428,  430,  437,
      435,    0,  435,  452,  446,  454,    0,  444,  457,  450,
      450,  454,  470,  464,    0,    0,    0,  459,  470,  461,
      463,  479,  467,  468,  486,    0,  485,    0,    0,  474,
      479,  478,    0,  479,    0,    0,  497,  485,  487,    0,
      501,    0,    0,  497,    0,    0,  500,  499,    0,  503,

      498,  503,  505,    0,  522,    0,  524,    0,    0,  525,
      526,    0,    0,  533,  526,    0,  522,  534,  526,  526,
      527,  541,  529,    0,    0,  541,  545,  539,  538,  557,
      545,    0,    0,  637,  609,  613,  617,  621,   91,  625,
      628,  632
    } ;

static yyconst flex_int16_t yy_def[343] =
    {   0,
      334,    1,  335,  335,  336,  336,  334,  334,  334,  334,
      334,  337,  334,  334,  338,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  334,  334,  334,
      334,  334,  334,  340,  334,  341,  334,  334,  334,  337,
      334,  334,  338,  334,  334,  334,  334,  334,  342,  334,
      334,  334,  334,  334,  334,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,

      339,  339,  339,  339,  339,  339,  334,  340,  341,  341,
      334,  334,  342,  334,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,

      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,

      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,    0,  334,  334,  334,  334,  334,  334,
      334,  334
    } ;

static yyconst flex_uint16_t yy_nxt[712] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       32,   38,   39,   32,   32,   40,   41,   42,   32,   43,
       44,   45,   46,   32,   47,   32,   48,   49,   50,    8,
       32,   33,   34,   35,   36,   37,   32,   38,   39,   32,
       40,   41,   42,   32,   43,   44,   45,   46,   32,   47,
       32,   51,   52,   53,   55,   55,   68,   71,   77,   72,
       78,   69,   56,   56,   81,   85,   70,   88,   82,   89,
      110,   79,   83,   76,   80,  111,   84,   86,   90,   92,

       98,   87,   91,   77,   99,  104,   78,   71,  115,   72,
       81,   85,   88,   82,  269,   89,   79,   83,   93,   80,
       94,   84,  212,   86,   90,   92,   98,   87,   91,  118,
       99,  104,  119,  115,   95,  123,   96,  100,  114,   97,
      105,  101,  120,   93,  106,  121,   94,  102,  116,  117,
      124,  125,  103,  126,  127,  118,  129,  119,  122,   95,
      123,   96,  130,  100,   97,  131,  105,  101,  120,  128,
      106,  121,  102,  116,  117,  124,  125,  103,  126,  132,
      127,  129,  133,  122,  134,  135,  141,  130,  137,  138,
      139,  131,  136,  142,  128,  143,  140,  145,  144,  146,

      147,  148,  114,  150,  132,  151,   64,  152,  133,  154,
      134,  135,  141,  137,  138,  149,  139,  136,  142,  153,
      143,  140,  145,  144,  146,  334,  147,  148,  150,  110,
      334,  151,  152,  155,  111,  154,  156,  157,  160,  161,
      149,  162,  163,  164,  153,  165,   61,  166,  167,  112,
      168,  169,  107,  158,  170,  159,  171,  172,  155,  173,
      174,  156,  175,  157,  160,  161,  176,  162,  163,  164,
      177,  165,  166,  178,  167,  168,  179,  169,  158,  170,
      159,  171,  172,  180,  173,  174,  182,  183,  175,  186,
      181,  176,  184,  185,  187,  177,  188,  189,  190,  178,

      191,  192,  179,  193,  194,  195,  196,  197,  180,  198,
      199,  182,  183,  200,  186,  181,  201,  202,  184,  185,
      187,  188,  189,  203,  190,  204,  191,  192,  205,  193,
      194,  195,  196,  197,  206,  198,  199,  207,  208,  200,
      209,  201,  210,  202,  211,  213,   75,  214,  203,  215,
      204,  216,  217,  205,  218,  219,  220,   74,  221,  206,
      222,  223,  207,  224,  208,  225,  209,  210,  226,  230,
      211,  213,  214,  227,  215,  228,  229,  216,  217,  231,
      218,  219,  220,  221,  232,  222,  223,  233,  234,  224,
      235,  225,  236,  238,  226,  230,  237,  239,  227,  240,

      228,  229,  241,   73,  242,  231,  243,  244,  245,  232,
      246,  247,  233,  234,  248,  235,  249,  250,  236,  238,
      251,  237,  239,  252,  253,  240,  254,  255,  241,  242,
      256,  243,  244,  257,  245,  246,  258,  247,  259,  261,
      248,  260,  249,  250,  262,  268,  251,  263,  252,  264,
      253,  254,  265,  255,  266,  256,  267,  270,  271,  257,
      272,  273,  258,  274,  259,  261,  260,  275,  276,  277,
      262,  268,  263,  278,  264,  279,  280,  265,  281,  266,
      282,  267,  283,  270,  271,  284,  272,  273,  285,  274,
      286,  287,  275,  276,  288,  277,  289,  291,  278,  290,

      279,  292,  280,  293,  281,  294,  282,  283,  295,  296,
      297,  284,  298,  285,  299,  286,  287,  300,  301,  302,
      288,  303,  289,  291,  290,  304,  292,  305,  293,  306,
      311,  294,  307,  295,  296,  308,  297,  309,  298,  299,
      310,  312,  300,  301,  302,  313,  314,  303,  315,  316,
      304,  317,  305,  320,  321,  306,  311,  307,  322,  318,
      308,  319,  309,  323,  324,  310,  312,  325,  326,  328,
      313,  327,  314,  329,  315,  316,  330,  317,  331,  320,
      321,  332,   67,  333,  322,  318,   66,  319,  323,  324,
       65,   64,  325,   62,  326,  328,  327,   61,   59,  329,

      334,  330,   58,  331,   58,  334,  334,  332,  333,   54,
       54,   54,   54,   57,   57,   57,   57,   60,   60,   60,
       60,   63,   63,   63,   63,  108,  334,  108,  109,  334,
      109,  109,  113,  334,  113,  113,    7,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,

      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334
    } ;

static yyconst flex_int16_t yy_chk[712] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,   23,   24,   33,   24,
       34,   23,    3,    4,   35,   37,   23,   39,   36,   40,
       56,   34,   36,  339,   34,   56,   36,   38,   41,   42,

       44,   38,   41,   33,   44,   46,   34,   72,   77,   72,
       35,   37,   39,   36,  241,   40,   34,   36,   42,   34,
       43,   36,  172,   38,   41,   42,   44,   38,   41,   79,
       44,   46,   80,   77,   43,   82,   43,   45,  114,   43,
       47,   45,   81,   42,   47,   81,   43,   45,   78,   78,
       83,   84,   45,   85,   86,   79,   87,   80,   81,   43,
       82,   43,   88,   45,   43,   89,   47,   45,   81,   86,
       47,   81,   45,   78,   78,   83,   84,   45,   85,   90,
       86,   87,   91,   81,   92,   93,   97,   88,   94,   95,
       96,   89,   93,   98,   86,   99,   96,  100,   99,  101,

      102,  103,   71,  104,   90,  105,   63,  106,   91,  116,
       92,   93,   97,   94,   95,  103,   96,   93,   98,  115,
       99,   96,  100,   99,  101,  109,  102,  103,  104,  110,
      109,  105,  106,  117,  110,  116,  118,  119,  120,  121,
      103,  122,  123,  124,  115,  125,   60,  126,  127,   58,
      128,  129,   52,  119,  130,  119,  130,  131,  117,  132,
      133,  118,  134,  119,  120,  121,  135,  122,  123,  124,
      136,  125,  126,  137,  127,  128,  138,  129,  119,  130,
      119,  130,  131,  139,  132,  133,  140,  141,  134,  144,
      139,  135,  142,  143,  145,  136,  146,  147,  148,  137,

      149,  150,  138,  151,  152,  153,  154,  156,  139,  157,
      158,  140,  141,  159,  144,  139,  160,  161,  142,  143,
      145,  146,  147,  162,  148,  163,  149,  150,  165,  151,
      152,  153,  154,  156,  166,  157,  158,  167,  168,  159,
      169,  160,  170,  161,  171,  173,   29,  174,  162,  176,
      163,  179,  180,  165,  181,  182,  183,   28,  184,  166,
      185,  186,  167,  187,  168,  189,  169,  170,  190,  194,
      171,  173,  174,  191,  176,  192,  193,  179,  180,  195,
      181,  182,  183,  184,  196,  185,  186,  198,  199,  187,
      200,  189,  201,  203,  190,  194,  202,  204,  191,  205,

      192,  193,  209,   27,  210,  195,  211,  212,  213,  196,
      214,  216,  198,  199,  217,  200,  218,  219,  201,  203,
      220,  202,  204,  221,  222,  205,  223,  224,  209,  210,
      225,  211,  212,  226,  213,  214,  228,  216,  230,  232,
      217,  231,  218,  219,  233,  240,  220,  234,  221,  235,
      222,  223,  236,  224,  237,  225,  238,  242,  243,  226,
      244,  245,  228,  246,  230,  232,  231,  248,  249,  250,
      233,  240,  234,  251,  235,  253,  254,  236,  255,  237,
      256,  238,  258,  242,  243,  259,  244,  245,  260,  246,
      261,  262,  248,  249,  263,  250,  264,  269,  251,  268,

      253,  270,  254,  271,  255,  272,  256,  258,  273,  274,
      275,  259,  277,  260,  280,  261,  262,  281,  282,  284,
      263,  287,  264,  269,  268,  288,  270,  289,  271,  291,
      301,  272,  294,  273,  274,  297,  275,  298,  277,  280,
      300,  302,  281,  282,  284,  303,  305,  287,  307,  310,
      288,  311,  289,  315,  317,  291,  301,  294,  318,  314,
      297,  314,  298,  319,  320,  300,  302,  321,  322,  326,
      303,  323,  305,  327,  307,  310,  328,  311,  329,  315,
      317,  330,   21,  331,  318,  314,   19,  314,  319,  320,
       18,   15,  321,   14,  322,  326,  323,   12,   11,  327,

        7,  328,    6,  329,    5,    0,    0,  330,  331,  335,
      335,  335,  335,  336,  336,  336,  336,  337,  337,  337,
      337,  338,  338,  338,  338,  340,    0,  340,  341,    0,
      341,  341,  342,    0,  342,  342,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,

      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[93] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 
    0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexico.l"
#line 5 "lexico.l"
#include "../Sintactico/parser.h"
#define YY_USER_ACTION yylloc.first_line = yylloc.last_line = nLinea;
#include "Coline/Elementos/Global/importar.h"

#import "Coline/Elementos/Tablas/tablasimbolos.h"

int nLinea=0;
tablaSimbolos *tabla33;
void iniciarLineaL(tablaSimbolos *tabla2){
        nLinea=1; 
        tabla33=tabla2; 
}

 

#line 771 "scanner.cpp"

#define INITIAL 0
#define comment 1
#define foo 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

			int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 31 "lexico.l"

        int comment_caller;

#line 995 "scanner.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 335 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 637 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 34 "lexico.l"
{
             comment_caller = INITIAL;
             BEGIN(comment);
             }
	YY_BREAK
/*
    =============================
        Simbolos
    =============================
    */
case 2:
YY_RULE_SETUP
#line 47 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return sMas; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 48 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return sMenos; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 49 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return sPor; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 50 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return sDiv; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 51 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return sPot; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 52 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return sMod; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 54 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return sIgualacion; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 55 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return sDiferenciacion; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 56 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return sMenorQue; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 57 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return sMayorQue; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 58 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return sMenorIgualQue; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 59 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return sMayorIgualQue; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 60 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return sAnd; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 61 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return sOr; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 62 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return sNot; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 65 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return sMasIgual; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 66 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return sMenosIgual; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 67 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return sPorIgual; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 68 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return sDivIgual; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 71 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return sAbreParent; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 72 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return sCierraParent; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 74 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return sAbreLlave; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 75 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return sCierraLlave; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 77 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return sAbreCorchete; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 78 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return sCierraCorchete; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 79 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return sPunto; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 80 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return sComa; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 81 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return sPuntoComa; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 82 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return sArroba; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 83 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return sIgual; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 85 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return sCierraInterrogante; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 86 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return sDosPuntos; }
	YY_BREAK
/*
    =============================
        Palabras reservadas
    =============================
    */
case 34:
YY_RULE_SETUP
#line 94 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tImport; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 95 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tClase; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 96 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tExtender; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 97 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tPadre; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 98 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tPrincipal; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 99 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tOverride; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 100 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tNuevo; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 101 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tEste; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 102 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tImprimir; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 103 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tConcatenar; }  
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 104 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tConvertirCadena; }  
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 105 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tConvertirNumero; }  
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 106 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tRetorno; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 107 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tSi; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 108 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tSino; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 109 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tCaso; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 110 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tSelecciona; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 111 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tDe; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 112 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tDefecto; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 113 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tRomper; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 114 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tMientras; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 115 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tContinuar; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 116 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tPara; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 117 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tHacer; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 118 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tRepetir; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 119 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tHasta; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 120 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tMensaje; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 121 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tSubCad; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 122 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tPosCad; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 123 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tRandom; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 124 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tTamanio; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 125 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tLeerTeclado; }
	YY_BREAK
/* "tam"               { strcpy(yylval.TEXT, yytext); return tTam; }*/
case 66:
YY_RULE_SETUP
#line 128 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tSuper; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 131 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tNada; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 132 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tVacio; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 133 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tNulo; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 135 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tEntero; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 136 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tCaracter; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 137 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tDecimal; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 138 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tBooleano; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 141 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tPublico; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 142 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tPrivado; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 143 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return tProtegido; }
	YY_BREAK
case 77:
/* rule 77 can match eol */
YY_RULE_SETUP
#line 145 "lexico.l"
{ nLinea++;}
	YY_BREAK
/*
    =============================
        Valores
    =============================
    */ 
case 78:
YY_RULE_SETUP
#line 152 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return valBoolean; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 153 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return valId; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 154 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return valNumero; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 155 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return valDecimal; }
	YY_BREAK
case 82:
/* rule 82 can match eol */
YY_RULE_SETUP
#line 156 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return valCaracter; }
	YY_BREAK
case 83:
/* rule 83 can match eol */
YY_RULE_SETUP
#line 157 "lexico.l"
{ strcpy(yylval.TEXT, yytext); return valCadena; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 159 "lexico.l"
{ /*Se ignoran*/ }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 160 "lexico.l"
{
                    //std::cout <<"Error léxico en linea:"<<nLinea<<" token:"<<yytext<<std::endl;
                    tabla33->tablaError->insertErrorLexical("--",nLinea,10,"No se reconoce el token: "+QString::fromUtf8(yytext));
                }
	YY_BREAK
/*
    =============================
        Comentarios
    =============================
    */ 
case 86:
YY_RULE_SETUP
#line 172 "lexico.l"
{ /* Comentario de una linea */ }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 174 "lexico.l"
{
    comment_caller = foo;
    BEGIN(comment);
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 179 "lexico.l"
/* eat anything that's not a '*' */
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 180 "lexico.l"
/* eat up '*'s not followed by '/'s */
	YY_BREAK
case 90:
/* rule 90 can match eol */
YY_RULE_SETUP
#line 181 "lexico.l"
++nLinea;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 182 "lexico.l"
BEGIN(comment_caller);
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 184 "lexico.l"
ECHO;
	YY_BREAK
#line 1556 "scanner.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment):
case YY_STATE_EOF(foo):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 335 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 335 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
	yy_is_jam = (yy_current_state == 334);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,(int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 184 "lexico.l"



